* cl-plot

** License

**********************************************************************
Copyright (c) 2018 Orm Finnendahl <orm.finnendahl@selma.hfmdk-frankfurt.de>
;;;
Revision history: See git repository.
;;;
This program is free software; you can redistribute it and/or
modify it under the terms of the Gnu Public License, version 2 or
later. See https://www.gnu.org/licenses/gpl-2.0.html for the text
of this agreement.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
;;;
**********************************************************************

cl-plot is a thin Common Lisp Wrapper for gnuplot. It expects gnuplot
at /usr/bin/gnuplot (change to your needs).

The central method is plot, which at this point accepts lists,
one-dimensional arrays or functions.

** INSTALLATION
   cl-plot depends on uiop. 

   The recommended way is to use quicklisp and put the cl-plot folder
   into <home>/quicklisp/local-projects/.

   Then load it with

   #+BEGIN_SRC lisp
     (ql:quickload "cl-plot")

     (in-package :cl-plot)

     ;;; plotting data lists:

     ;;; 2-dimensional:

     (plot
      (loop for count below 20
         collect (list count (random 40.0)))
      :grid nil)

     ;;; 1-dimensional:

     (plot
      (loop for count below 20
         collect (random 40.0)))


     ;;; plotting arrays:

     (plot #(3 1 8 6 5 2 4))

     (plot #((0 3) (1 1) (2 8) (3 6) (4 5) (5 2) (6 4)))

     (plot #(#(0 3) #(1 1) #(2 8) #(3 6) #(4 5) #(5 2) #(6 4)))


     ;;; plotting functions:

     (plot #'sin :region `(0 ,(* 2 pi)))

     (plot #'exp :region `(0 4))

     ;; default region is '(0 1)

     (plot #'sin)

   #+END_SRC

